/**
 * app.js — TG Scanner v2 main application with Supabase
 */

import { ensureGramReady } from './telegram.js';
import { beginLogin, submitOtp, submitPassword } from './auth.js';
import { searchGroups, scanGroups } from './scanner.js';
import { generateKeywords, scoreLeads, generateDmDraft } from './gemini.js';
import { loadSessionsFromDB, supabase } from './db.js'; // 🔥 Imported DB
import {
  renderNav, renderMenu, renderAccounts, renderGroups, renderCandidates,
  renderLoginModal, renderDmModal, renderStepper, renderOperation, showToast,
  updateButtons, escapeHtml,
} from './ui.js';

const API_ID = 39942557;
const API_HASH = '77a67551c7f83be89c33da3a95eefea0';

const STORAGE_KEYS = {
  accounts: 'tg_scanner2_accounts_v1',
  activePhone: 'tg_scanner2_active_phone_v1',
  geminiKey: 'tg_scanner2_gemini_key_v1',
};

const state = {
  gram: null,
  gramLoading: true,
  gramError: '',
  accounts: {},
  activePhone: '',
  clients: new Map(),
  groups: [],
  candidates: [],
  keywords: [],
  authFlow: null,
  dmLead: null,
  operation: { label: 'Idle', done: 0, total: 0 },
  ui: { loginOpen: false, dmOpen: false, menuOpen: false },
};

const els = {};

function cacheElements() {
  const ids = [
    'gram-badge', 'active-account-badge', 'active-initials', 'active-name',
    'menu-btn', 'kebab-menu', 'menu-accounts-list', 'menu-gemini-btn',
    'menu-stats-btn', 'menu-stats-panel', 'stat-groups', 'stat-candidates',
    'stat-accounts', 'progress-bar-wrap', 'progress-label', 'progress-pct', 
    'progress-fill', 'stepper', 'login-panel', 'accounts-list', 'add-account-btn',
    'search-panel', 'niche-input', 'gen-keywords-btn', 'search-groups-btn',
    'keywords-chips', 'scan-panel', 'groups-grid', 'select-all-btn', 'scan-btn',
    'outreach-panel', 'base-template', 'candidates-grid', 'login-modal', 
    'close-login-modal', 'login-phone-input', 'send-otp-btn', 'login-step-phone', 
    'login-step-otp', 'login-otp-input', 'verify-otp-btn', 'login-step-password', 
    'login-password-input', 'verify-password-btn', 'login-status', 'dm-modal', 
    'close-dm-modal', 'dm-candidate-info', 'dm-text', 'regen-dm-btn', 'send-dm-btn', 
    'dm-status', 'gemini-modal', 'close-gemini-modal', 'gemini-key-input', 
    'save-gemini-btn', 'toast-container',
  ];

  ids.forEach((id) => {
    const key = id.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
    els[key] = document.getElementById(id);
  });
  els.tabBtns = document.querySelectorAll('.tab-btn');
}

function render() {
  renderNav(state, els); renderMenu(state, els);
  renderAccounts(state, els, { onActivate: activateAccount, onLogout: logoutAccount });
  renderGroups(state, els, { onToggle: toggleGroup });
  renderCandidates(state, els, { onSendDm: openDmModal });
  renderLoginModal(state, els); renderDmModal(state, els);
  renderStepper(state, els); renderOperation(state, els);
  updateButtons(state, els); renderKeywordsChips();
}

function openLoginModal() {
  state.authFlow = null;
  if (els.loginPhoneInput) els.loginPhoneInput.value = '';
  if (els.loginOtpInput) els.loginOtpInput.value = '';
  if (els.loginPasswordInput) els.loginPasswordInput.value = '';
  state.ui.loginOpen = true;
  render();
  setTimeout(() => els.loginPhoneInput?.focus(), 80);
}

function closeLoginModal() { state.ui.loginOpen = false; state.authFlow = null; render(); }

function openDmModal(lead) {
  state.dmLead = lead; state.ui.dmOpen = true;
  if (els.dmText) els.dmText.value = '';
  if (els.dmStatus) els.dmStatus.classList.add('hidden');
  render(); _autoGenerateDm(lead);
}

function closeDmModal() { state.ui.dmOpen = false; state.dmLead = null; render(); }

function activateAccount(phone) {
  state.activePhone = phone;
  localStorage.setItem(STORAGE_KEYS.activePhone, phone);
  render();
}

// 🔥 LOGOUT UPDATED TO DELETE FROM DB 🔥
async function logoutAccount(phone) {
  const client = state.clients.get(phone);
  if (client) {
    client.disconnect().catch(() => {});
    state.clients.delete(phone);
  }

  delete state.accounts[phone];
  localStorage.setItem(STORAGE_KEYS.accounts, JSON.stringify(state.accounts));
  await supabase.from('telegram_sessions').delete().eq('phone', phone); // Delete from DB

  if (state.activePhone === phone) {
    state.activePhone = Object.keys(state.accounts)[0] || '';
    localStorage.setItem(STORAGE_KEYS.activePhone, state.activePhone);
  }

  showToast(`Account ${phone} removed`, 'info', els.toastContainer);
  render();
}

function toggleGroup(username) {
  const g = state.groups.find((g) => g.username === username);
  if (g) { g.selected = !g.selected; render(); }
}

async function connectSavedSession(phone, accountData) {
  if (!state.gram || !accountData.session) return;
  const { TelegramClient, StringSession } = state.gram;
  try {
    const sess = new StringSession(accountData.session);
    const client = new TelegramClient(sess, API_ID, API_HASH, { connectionRetries: 3, useWSS: true });
    await client.connect();
    state.clients.set(phone, client);
    console.info('[App] Session reconnected:', phone);
  } catch (err) {
    console.warn('[App] Session reconnect failed:', phone, err.message);
  }
}

function handleAuthStateChange(authState) {
  state.authFlow = authState;
  if (authState.step === 'done') {
    const { phone, name, username, initials, session: sessionStr, client } = authState;
    state.accounts[phone] = { phone, name, username, initials, session: sessionStr };
    state.activePhone = phone;
    if (client) state.clients.set(phone, client);
    showToast(`Welcome, ${name}! ✅`, 'success', els.toastContainer);
    setTimeout(closeLoginModal, 1500);
  } else if (authState.step === 'error') {
    showToast(authState.message || 'Login failed', 'error', els.toastContainer);
  }
  render();
}

function getGeminiKey() { return localStorage.getItem(STORAGE_KEYS.geminiKey) || ''; }

async function _autoGenerateDm(lead) {
  const geminiKey = getGeminiKey();
  if (!geminiKey) { if (els.dmText) els.dmText.value = els.baseTemplate?.value || ''; return; }
  if (els.dmStatus) { els.dmStatus.textContent = 'Generating personalized DM…'; els.dmStatus.classList.remove('hidden'); }
  try {
    const draft = await generateDmDraft(els.baseTemplate?.value || '', lead, geminiKey);
    if (els.dmText) els.dmText.value = draft;
  } catch (err) {
    if (els.dmText) els.dmText.value = els.baseTemplate?.value || '';
  } finally {
    if (els.dmStatus) els.dmStatus.classList.add('hidden');
  }
}

function renderKeywordsChips() {
  if (!els.keywordsChips) return;
  if (!state.keywords.length) { els.keywordsChips.innerHTML = ''; return; }
  els.keywordsChips.innerHTML = state.keywords.map(kw => `<span class="px-3 py-1 bg-blue-500/20 text-blue-300 border border-blue-500/30 rounded-full text-xs cursor-default">${escapeHtml(kw)}</span>`).join('');
}

function getActiveClient() { return state.clients.get(state.activePhone) || state.clients.values().next().value || null; }

function bindEvents() {
  els.menuBtn?.addEventListener('click', (e) => { e.stopPropagation(); state.ui.menuOpen = !state.ui.menuOpen; renderMenu(state, els); });
  document.addEventListener('click', () => { if (state.ui.menuOpen) { state.ui.menuOpen = false; renderMenu(state, els); } });
  els.kebabMenu?.addEventListener('click', (e) => e.stopPropagation());
  els.menuAccountsList?.addEventListener('click', (e) => {
    const btn = e.target.closest('[data-menu-activate]');
    if (btn) { activateAccount(btn.dataset.menuActivate); state.ui.menuOpen = false; renderMenu(state, els); }
  });
  els.menuGeminiBtn?.addEventListener('click', () => {
    state.ui.menuOpen = false; renderMenu(state, els);
    if (els.geminiKeyInput) els.geminiKeyInput.value = getGeminiKey();
    _openModal(els.geminiModal);
  });
  els.menuStatsBtn?.addEventListener('click', () => els.menuStatsPanel?.classList.toggle('hidden'));
  els.closeGeminiModal?.addEventListener('click', () => _closeModal(els.geminiModal));
  els.saveGeminiBtn?.addEventListener('click', () => {
    localStorage.setItem(STORAGE_KEYS.geminiKey, els.geminiKeyInput?.value.trim() || '');
    showToast('Gemini API key saved ✅', 'success', els.toastContainer);
    _closeModal(els.geminiModal);
  });
  els.addAccountBtn?.addEventListener('click', openLoginModal);
  els.closeLoginModal?.addEventListener('click', closeLoginModal);
  
  els.sendOtpBtn?.addEventListener('click', async () => {
    const phone = els.loginPhoneInput?.value.trim() || '';
    if (!phone.startsWith('+')) { showToast('Phone must start with +', 'error', els.toastContainer); return; }
    let gram = state.gram;
    if (!gram) {
      state.authFlow = { step: 'sending', message: 'Loading GramJS…' }; render();
      try { gram = await ensureGramReady(); state.gram = gram; state.gramLoading = false; state.gramError = ''; renderNav(state, els); } 
      catch (err) { state.gramLoading = false; state.gramError = err.message; showToast('GramJS failed', 'error', els.toastContainer); state.authFlow = { step: 'error', message: 'GramJS failed to load.' }; render(); return; }
    }
    beginLogin(phone, gram, handleAuthStateChange);
  });
  els.verifyOtpBtn?.addEventListener('click', () => {
    const code = els.loginOtpInput?.value.trim() || '';
    if (!code) { showToast('Enter OTP', 'error', els.toastContainer); return; }
    state.authFlow = { ...state.authFlow, step: 'verifying', message: 'Verifying OTP…' }; render(); submitOtp(code);
  });
  els.loginOtpInput?.addEventListener('keydown', (e) => { if (e.key === 'Enter') els.verifyOtpBtn?.click(); });
  els.loginPhoneInput?.addEventListener('keydown', (e) => { if (e.key === 'Enter') els.sendOtpBtn?.click(); });
  els.verifyPasswordBtn?.addEventListener('click', () => {
    const pass = els.loginPasswordInput?.value || '';
    if (!pass) { showToast('Enter password', 'error', els.toastContainer); return; }
    submitPassword(pass);
  });
  els.loginPasswordInput?.addEventListener('keydown', (e) => { if (e.key === 'Enter') els.verifyPasswordBtn?.click(); });
  
  els.closeDmModal?.addEventListener('click', closeDmModal);
  els.regenDmBtn?.addEventListener('click', () => { if (state.dmLead) _autoGenerateDm(state.dmLead); });
  els.sendDmBtn?.addEventListener('click', async () => {
    const text = els.dmText?.value.trim() || ''; if (!text || !state.dmLead) return;
    const client = getActiveClient(); if (!client) { showToast('No active Telegram account!', 'error', els.toastContainer); return; }
    if (els.sendDmBtn) els.sendDmBtn.disabled = true;
    if (els.dmStatus) { els.dmStatus.textContent = 'Sending…'; els.dmStatus.classList.remove('hidden'); }
    try {
      await client.sendMessage(state.dmLead.username, { message: text });
      showToast('DM sent! ✅', 'success', els.toastContainer); closeDmModal();
    } catch (err) { showToast('Failed: ' + err.message, 'error', els.toastContainer); if (els.dmStatus) els.dmStatus.textContent = 'Error: ' + err.message; } 
    finally { if (els.sendDmBtn) els.sendDmBtn.disabled = false; }
  });

  els.genKeywordsBtn?.addEventListener('click', async () => {
    const niche = els.nicheInput?.value.trim() || ''; if (!niche) { showToast('Enter a niche first', 'error', els.toastContainer); return; }
    const geminiKey = getGeminiKey(); if (!geminiKey) { showToast('Set Gemini API key first', 'error', els.toastContainer); return; }
    if (els.genKeywordsBtn) { els.genKeywordsBtn.disabled = true; els.genKeywordsBtn.innerHTML = '<i class="fa-solid fa-circle-notch fa-spin mr-2"></i>Generating…'; }
    try {
      const keywords = await generateKeywords(niche, geminiKey);
      state.keywords = keywords; renderKeywordsChips(); showToast(`Generated ${keywords.length} keywords!`, 'success', els.toastContainer);
    } catch (err) { showToast('Generation failed: ' + err.message, 'error', els.toastContainer); } 
    finally { if (els.genKeywordsBtn) { els.genKeywordsBtn.disabled = false; els.genKeywordsBtn.innerHTML = '<i class="fa-solid fa-wand-magic-sparkles mr-2"></i>AI Keywords'; } }
  });

  els.searchGroupsBtn?.addEventListener('click', async () => {
    const client = getActiveClient(); if (!client) { showToast('Login first!', 'error', els.toastContainer); return; }
    if (!state.gram) { showToast('GramJS not ready', 'error', els.toastContainer); return; }
    let keywords = [...state.keywords];
    if (!keywords.length) { const niche = els.nicheInput?.value.trim() || ''; if (!niche) { showToast('Enter niche/keywords', 'error', els.toastContainer); return; } keywords = [niche]; }
    if (els.searchGroupsBtn) { els.searchGroupsBtn.disabled = true; els.searchGroupsBtn.innerHTML = '<i class="fa-solid fa-circle-notch fa-spin mr-2"></i>Searching…'; }
    state.operation = { label: 'Searching groups…', done: 0, total: keywords.length }; renderOperation(state, els);
    try {
      state.groups = await searchGroups(keywords, client, state.gram.Api, (done, total, kw) => { state.operation = { label: `Searching: "${kw}"`, done, total }; renderOperation(state, els); });
      showToast(`Found ${state.groups.length} groups!`, 'success', els.toastContainer);
    } catch (err) { showToast('Search failed: ' + err.message, 'error', els.toastContainer); } 
    finally { if (els.searchGroupsBtn) { els.searchGroupsBtn.disabled = false; els.searchGroupsBtn.innerHTML = '<i class="fa-solid fa-magnifying-glass mr-2"></i>Find Groups'; } state.operation = { label: 'Idle', done: 0, total: 0 }; render(); }
  });

  els.selectAllBtn?.addEventListener('click', () => { const allSelected = state.groups.length > 0 && state.groups.every((g) => g.selected); state.groups.forEach((g) => { g.selected = !allSelected; }); render(); });

  els.scanBtn?.addEventListener('click', async () => {
    const client = getActiveClient(); if (!client) { showToast('Login first!', 'error', els.toastContainer); return; }
    const selectedGroups = state.groups.filter((g) => g.selected); if (!selectedGroups.length) { showToast('Select group', 'error', els.toastContainer); return; }
    const geminiKey = getGeminiKey(); if (!geminiKey) { showToast('Set Gemini Key', 'error', els.toastContainer); return; }
    if (els.scanBtn) { els.scanBtn.disabled = true; els.scanBtn.innerHTML = '<i class="fa-solid fa-circle-notch fa-spin mr-2"></i>Scanning…'; }
    state.operation = { label: 'Scanning groups…', done: 0, total: selectedGroups.length }; renderOperation(state, els);
    try {
      const messages = await scanGroups(selectedGroups, client, (done, total, gName) => { state.operation = { label: `Scanning: "${gName}"`, done, total }; renderOperation(state, els); });
      if (!messages.length) { showToast('No messages found', 'info', els.toastContainer); return; }
      state.operation = { label: `Scoring ${messages.length} profiles with AI…`, done: 0, total: 1 }; renderOperation(state, els);
      const scored = await scoreLeads(messages, geminiKey);
      state.candidates = scored.filter((c) => c.score > 50).sort((a, b) => b.score - a.score);
      showToast(`Found ${state.candidates.length} candidates!`, 'success', els.toastContainer);
    } catch (err) { showToast('Scan failed: ' + err.message, 'error', els.toastContainer); } 
    finally { if (els.scanBtn) { els.scanBtn.disabled = false; els.scanBtn.innerHTML = '<i class="fa-solid fa-satellite-dish mr-2"></i>Scan Leads'; } state.operation = { label: 'Idle', done: 0, total: 0 }; render(); }
  });

  els.tabBtns?.forEach((btn) => { btn.addEventListener('click', () => { const tab = btn.dataset.tab; _switchTab(tab); els.tabBtns.forEach((b) => { b.classList.toggle('text-blue-400', b.dataset.tab === tab); b.classList.toggle('text-slate-400', b.dataset.tab !== tab); }); }); });
}

function _switchTab(tab) {
  const panels = { login: els.loginPanel, search: els.searchPanel, scan: els.scanPanel, outreach: els.outreachPanel };
  Object.values(panels).forEach((p) => p?.classList.add('hidden')); panels[tab]?.classList.remove('hidden');
}

function _openModal(el) { if (!el) return; el.classList.remove('hidden'); el.classList.add('flex'); }
function _closeModal(el) { if (!el) return; el.classList.add('hidden'); el.classList.remove('flex'); }

async function boot() {
  cacheElements();

  // 🔥 LOAD SESSIONS FROM SUPABASE 🔥
  try {
    const dbAccounts = await loadSessionsFromDB();
    const accountsObj = {};
    dbAccounts.forEach(acc => {
      accountsObj[acc.phone] = {
        phone: acc.phone,
        name: acc.name || acc.phone,
        session: acc.session_string,
        initials: (acc.name || acc.phone).slice(0,2).toUpperCase()
      };
    });
    state.accounts = accountsObj;
  } catch (err) {
    console.error("DB Load Error", err);
    state.accounts = {};
  }
  
  state.activePhone = localStorage.getItem(STORAGE_KEYS.activePhone) || Object.keys(state.accounts)[0] || '';

  bindEvents();
  render();

  try {
    state.gram = await ensureGramReady();
    state.gramLoading = false;
    state.gramError = '';
    console.info('[App] GramJS ready ✅');
    renderNav(state, els);

    const reconnectPromises = Object.entries(state.accounts).map(
      ([phone, acc]) => connectSavedSession(phone, acc)
    );
    await Promise.allSettled(reconnectPromises);
    updateButtons(state, els);
  } catch (err) {
    state.gramLoading = false;
    state.gramError = err.message;
    console.error('[App] GramJS failed to load:', err);
    renderNav(state, els);
    showToast('GramJS failed: ' + err.message, 'error', els.toastContainer);
  }

  if (Object.keys(state.accounts).length === 0) {
    openLoginModal();
  }
}

document.addEventListener('DOMContentLoaded', boot);
